using UnityEngine;
using Sandsunder.Simulation;

namespace Sandsunder.Gameplay
{
    /// <summary>
    /// Sandstorm Golem Boss (Feature 3): a sandstone colossus with a floating cyan rune core.
    /// State machine: Idle -> Telegraph -> Charge -> Cooldown -> (loop). On death it plays a
    /// crumbling DeathBurst. The cyan rune core bobs with a Sine wave and glows additively.
    /// </summary>
    [DisallowMultipleComponent]
    [RequireComponent(typeof(PrototypeHealth), typeof(Rigidbody2D))]
    public sealed class SandstormGolemAI : MonoBehaviour
    {
        private enum GolemState { Idle, Telegraph, Charge, Cooldown, Dying }

        [SerializeField] private float chargeSpeed = 6.5f;
        [SerializeField] private float telegraphTime = 0.8f;
        [SerializeField] private float chargeTime = 1.4f;
        [SerializeField] private float cooldownTime = 1.2f;
        [SerializeField] private float runeBobAmplitude = 0.12f;
        [SerializeField] private float runeBobSpeed = 2.2f;
        [SerializeField] private Color runeGlow = new(0f, 0.94f, 0.90f);

        private GolemState state;
        private float stateTimer;
        private Vector2 chargeDirection = Vector2.right;
        private Rigidbody2D body;
        private SpriteRenderer runeCore;
        private Vector3 runeBasePosition;
        private PrototypeHealth health;

        private void Awake()
        {
            body = GetComponent<Rigidbody2D>();
            body.bodyType = RigidbodyType2D.Kinematic;
            body.gravityScale = 0f;
            health = GetComponent<PrototypeHealth>();
            BuildRuneCore();
        }

        private void BuildRuneCore()
        {
            GameObject go = new("GolemRuneCore");
            go.transform.SetParent(transform, false);
            go.transform.localPosition = new Vector3(0f, 0.55f, 0f);
            runeCore = go.AddComponent<SpriteRenderer>();
#if UNITY_EDITOR
            // CyanRune is generated by the editor art factory; load it directly so this runtime
            // assembly does not depend on the Editor assembly (avoids CS0234).
            runeCore.sprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sandsunder/Art/Generated/CyanRuneSprite.asset");
#endif
            runeCore.color = runeGlow;
            var mat = new Material(Shader.Find("Sprites/Default"));
            mat.color = new Color(runeGlow.r, runeGlow.g, runeGlow.b, 0.9f);
            runeCore.material = mat;
            runeCore.sortingOrder = 30;
            runeBasePosition = runeCore.transform.localPosition;
        }

        private void Update()
        {
            if (runeCore != null)
            {
                float wave = Mathf.Sin(Time.time * runeBobSpeed) * runeBobAmplitude;
                runeCore.transform.localPosition = runeBasePosition + new Vector3(0f, wave, 0f);
            }

            if (health != null && health.IsDead)
            {
                if (state != GolemState.Dying)
                {
                    state = GolemState.Dying;
                    SandboxVisualEffects.SpawnDust(transform.position, 24, new Color(0.86f, 0.70f, 0.43f));
                }
                return;
            }

            stateTimer -= Time.deltaTime;
            switch (state)
            {
                case GolemState.Idle:
                    if (stateTimer <= 0f) { state = GolemState.Telegraph; stateTimer = telegraphTime; }
                    break;
                case GolemState.Telegraph:
                    FaceNearbyPlayer();
                    if (stateTimer <= 0f) { state = GolemState.Charge; stateTimer = chargeTime; }
                    break;
                case GolemState.Charge:
                    body.linearVelocity = chargeDirection * chargeSpeed;
                    SandboxVisualEffects.SpawnDust(body.position, 1, new Color(0.86f, 0.70f, 0.43f));
                    if (stateTimer <= 0f) { body.linearVelocity = Vector2.zero; state = GolemState.Cooldown; stateTimer = cooldownTime; }
                    break;
                case GolemState.Cooldown:
                    if (stateTimer <= 0f) { state = GolemState.Idle; stateTimer = 0.6f; }
                    break;
            }
        }

        private void FaceNearbyPlayer()
        {
            PrototypePlayerCombat player = FindFirstObjectByType<PrototypePlayerCombat>();
            if (player == null) return;
            Vector2 offset = (Vector2)player.transform.position - body.position;
            if (offset.sqrMagnitude > 0.0001f) chargeDirection = offset.normalized;
        }

        private void OnTriggerEnter2D(Collider2D other)
        {
            if (state != GolemState.Charge) return;
            PrototypeHealth target = other.GetComponentInParent<PrototypeHealth>();
            if (target == null || target.Team == (health?.Team ?? 0)) return;
            if (other.GetComponent<SubterraneanStealth>()?.IsStealthed == true) return;
            target.TryDamage(new CombatDamageRequest(health.EntityId, health.Team, 40));
        }
    }
}